apiVersion: v1
kind: ConfigMap

metadata:
  name: hello-api-config

data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  APP_MESSAGE: "Hello Franklin, update  from kubernetes ConfigMap"

  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"